events {
    # Bloc obligatoire pour que Nginx démarre.
    # On le laisse vide pour la config par défaut.}
}

http {

    server {
        # Écoute le port sécurisé (HTTPS) en IPv4.
        listen 443 ssl;
        # Écoute le port sécurisé (HTTPS) en IPv6.
        listen [::]:443 ssl;

        # L'URL du site.
        server_name mcotonea.42.fr;

        # Chemins vers ton certificat public et ta clé privée (générés via OpenSSL).
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        # On force l'utlisation de protocoles récents.
        ssl_protocols TLSv1.2 TLSv1.3;

        # Le dossier racine où Nginx va chercher les fichiers du site.
        root /var/www/html;
        # L'ordre de priorité des fichiers d'accueil à afficher.
        index index.php index.html index.htm;

        location / {
            # 1. Cherche si le fichier existe ($uri).
            # 2. Cherche si le dossier existe ($uri/).
            # 3. Si rien n'existe, envoie la demande à WordPress (index.php) avec les arguments.
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            # Charge une config PHP par défaut (Attention : ce fichier n'existe pas toujours sur Alpine).
            include snippets/fastcgi-php.conf;

            # Envoie le code PHP à exécuter au conteneur "wordpress" sur le port 9000.
            fastcgi_pass wordpress:9000;
            # Indique à PHP le chemin complet du fichier à exécuter sur le disque.
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            # Charge les paramètres standards nécessaires à la communication Nginx <-> PHP.
            include fastcgi_params;
        }
    }
}
