[www]
; L'utilisateur www-data est l'utilisateur standard pour les services Web.
user = www-data
group = www-data
; Par defaut, PHP-FPM ecoute sur un socket Unix. Mais comme NGINX et PHP sont dans des 
; conteneurs differents, ils ne peut pas communiquer via un socket.
; PHP doit donc ecouter sur une adresse IP et un port reseau (9000).
; PHP accoete les connexions venant de n'importe quelle interface
listen = 0.0.0.0:9000
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
; On configure le gestionnaire de processus (Process Maganer)
; 'dynamic' signifie que le nombre de processus enfants s'adapte a la charge.
; max_children -> Definit la limite de requetes simultanees.
; start_servers -> definit le nombre de processus cree au demarrage du service.
; min_spare_servers -> le nombre minimum de processus en attente a garder en memoire.
; max_spare_servers -> le nombre maximum de processus en attente.
